-- AnnSetu database setup: every migration in order.
-- Paste this whole file into Supabase → SQL Editor → New query, then Run. Run it once, on a new project.
-- Generated by "npm run db:bundle"; edit the files in supabase/migrations instead.

-- ===== 20261004000001_schema.sql =====

-- AnnSetu schema: users' profiles, produce with its stock ledger, orders, buyer demand, reviews.
-- Quantities are numeric so "2.5 kg" works; money is numeric(12,2) rupees.

create type public.user_role as enum ('farmer', 'consumer');
create type public.consumer_type as enum ('individual', 'industrial');
create type public.unit as enum ('kg', 'quintal', 'tonne', 'dozen', 'piece', 'litre', 'bunch');
create type public.produce_category as enum ('vegetables', 'fruits', 'grains', 'pulses', 'spices', 'dairy', 'oilseeds', 'others');
create type public.produce_status as enum ('active', 'paused', 'sold_out', 'archived');
create type public.order_status as enum ('placed', 'accepted', 'rejected', 'packed', 'out_for_delivery', 'delivered', 'cancelled');
create type public.ledger_type as enum ('listed', 'restocked', 'reserved', 'released', 'sold', 'spoiled', 'adjusted');
create type public.demand_status as enum ('open', 'fulfilled', 'closed');
create type public.business_type as enum ('restaurant', 'retailer', 'wholesaler', 'processor', 'institution', 'other');

-- One row per auth user, created by the on_auth_user_created trigger.
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role public.user_role not null,
  consumer_type public.consumer_type,
  full_name text not null default '' check (char_length(full_name) <= 120),
  phone text check (phone is null or phone ~ '^[0-9+ -]{7,16}$'),
  avatar_url text check (avatar_url is null or char_length(avatar_url) <= 500),
  preferred_lang text not null default 'en' check (preferred_lang in ('en', 'hi')),
  onboarded boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint consumer_type_matches_role check ((role = 'consumer') = (consumer_type is not null))
);

create table public.farmer_details (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  farm_name text check (char_length(farm_name) <= 120),
  farm_size_acres numeric(10, 2) check (farm_size_acres is null or farm_size_acres >= 0),
  main_crops text[] not null default '{}' check (cardinality(main_crops) <= 20),
  updated_at timestamptz not null default now()
);

create table public.buyer_details (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  business_name text check (char_length(business_name) <= 160),
  business_type public.business_type,
  gstin text check (gstin is null or gstin ~ '^[0-9]{2}[A-Z0-9]{13}$'),
  updated_at timestamptz not null default now()
);

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  label text not null default 'home' check (char_length(label) <= 40),
  line1 text not null check (char_length(line1) between 1 and 200),
  line2 text check (char_length(line2) <= 200),
  village_city text not null check (char_length(village_city) between 1 and 120),
  district text not null check (char_length(district) between 1 and 120),
  state text not null check (char_length(state) between 1 and 80),
  pincode text not null check (pincode ~ '^[0-9]{6}$'),
  lat double precision check (lat between -90 and 90),
  lng double precision check (lng between -180 and 180),
  is_default boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index addresses_one_default on public.addresses (user_id) where is_default;

-- A farmer's listing. qty_available is derived; the four counters only change through the
-- functions in 20261004000002_functions.sql, which also write the produce_log ledger.
create table public.produce (
  id uuid primary key default gen_random_uuid(),
  farmer_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  category public.produce_category not null,
  name text not null check (char_length(name) between 1 and 80),
  variety text check (char_length(variety) <= 80),
  description text check (char_length(description) <= 2000),
  unit public.unit not null,
  price_per_unit numeric(12, 2) not null check (price_per_unit > 0),
  qty_listed numeric(14, 2) not null check (qty_listed >= 0),
  qty_sold numeric(14, 2) not null default 0 check (qty_sold >= 0),
  qty_reserved numeric(14, 2) not null default 0 check (qty_reserved >= 0),
  qty_spoiled numeric(14, 2) not null default 0 check (qty_spoiled >= 0),
  qty_available numeric(14, 2) generated always as (qty_listed - qty_sold - qty_reserved - qty_spoiled) stored,
  min_order_qty numeric(14, 2) not null default 1 check (min_order_qty > 0),
  harvest_date date,
  best_before date,
  is_organic boolean not null default false,
  images text[] not null default '{}' check (cardinality(images) <= 4),
  status public.produce_status not null default 'active',
  district text,
  state text,
  lat double precision,
  lng double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint produce_stock_non_negative check (qty_listed - qty_sold - qty_reserved - qty_spoiled >= 0),
  constraint produce_dates check (best_before is null or harvest_date is null or best_before >= harvest_date)
);
create index produce_farmer_idx on public.produce (farmer_id, created_at desc);
create index produce_market_idx on public.produce (status, category, created_at desc);

-- A checkout with items from several farmers becomes one order per farmer (same checkout_id).
-- Delivery, buyer and farmer details are snapshots taken when the order is placed.
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  checkout_id uuid not null,
  buyer_id uuid references public.profiles (id) on delete set null,
  farmer_id uuid references public.profiles (id) on delete set null,
  status public.order_status not null default 'placed',
  payment_method text not null default 'cod' check (payment_method = 'cod'),
  total numeric(14, 2) not null default 0,
  delivery_name text not null,
  delivery_phone text not null,
  delivery_line1 text not null,
  delivery_line2 text,
  delivery_village_city text not null,
  delivery_district text not null,
  delivery_state text not null,
  delivery_pincode text not null,
  delivery_lat double precision,
  delivery_lng double precision,
  delivery_notes text,
  buyer_name text not null,
  buyer_type public.consumer_type,
  farmer_name text not null,
  farmer_phone text,
  status_history jsonb not null default '[]'::jsonb,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index orders_farmer_idx on public.orders (farmer_id, created_at desc);
create index orders_buyer_idx on public.orders (buyer_id, created_at desc);
create index orders_checkout_idx on public.orders (checkout_id);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  produce_id uuid references public.produce (id) on delete set null,
  name text not null,
  unit public.unit not null,
  unit_price numeric(12, 2) not null,
  quantity numeric(14, 2) not null check (quantity > 0)
);
create index order_items_order_idx on public.order_items (order_id);
create index order_items_produce_idx on public.order_items (produce_id);

-- Append-only stock ledger behind each listing's "Stock log".
create table public.produce_log (
  id uuid primary key default gen_random_uuid(),
  produce_id uuid not null references public.produce (id) on delete cascade,
  farmer_id uuid not null references public.profiles (id) on delete cascade,
  change_type public.ledger_type not null,
  quantity numeric(14, 2) not null,
  note text check (char_length(note) <= 300),
  order_id uuid references public.orders (id) on delete set null,
  created_at timestamptz not null default now()
);
create index produce_log_produce_idx on public.produce_log (produce_id, created_at desc);

-- What buyers need. Open requests feed the farmers' suggestion panel.
create table public.demand_requests (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  category public.produce_category not null default 'others',
  item_name text not null check (char_length(item_name) between 1 and 80),
  quantity numeric(14, 2) not null check (quantity > 0),
  unit public.unit not null,
  target_price numeric(12, 2) check (target_price is null or target_price > 0),
  needed_by date,
  notes text check (char_length(notes) <= 1000),
  district text,
  state text,
  lat double precision,
  lng double precision,
  status public.demand_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index demand_open_idx on public.demand_requests (status, created_at desc);
create index demand_buyer_idx on public.demand_requests (buyer_id, created_at desc);

-- One rating per delivered order.
create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders (id) on delete cascade,
  buyer_id uuid references public.profiles (id) on delete set null,
  farmer_id uuid not null references public.profiles (id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text check (char_length(comment) <= 1000),
  reviewer_name text not null default '',
  created_at timestamptz not null default now()
);
create index reviews_farmer_idx on public.reviews (farmer_id, created_at desc);

-- Public, privacy-trimmed views. They run with the owner's rights, so they expose only the
-- columns listed here: no phone numbers, and coordinates rounded to about 1 km.
create view public.farmer_ratings as
select farmer_id, round(avg(rating)::numeric, 1)::float8 as avg_rating, count(*)::int as ratings_count
from public.reviews
group by farmer_id;

create view public.market_listings as
select
  p.id, p.farmer_id, p.category, p.name, p.variety, p.description, p.unit, p.price_per_unit,
  p.qty_available, p.min_order_qty, p.harvest_date, p.best_before, p.is_organic, p.images, p.status,
  p.district, p.state,
  round(p.lat::numeric, 2)::float8 as approx_lat,
  round(p.lng::numeric, 2)::float8 as approx_lng,
  p.created_at,
  pr.full_name as farmer_name,
  fd.farm_name,
  pr.avatar_url as farmer_avatar,
  r.avg_rating as farmer_rating,
  coalesce(r.ratings_count, 0) as farmer_ratings_count
from public.produce p
join public.profiles pr on pr.id = p.farmer_id
left join public.farmer_details fd on fd.user_id = p.farmer_id
left join public.farmer_ratings r on r.farmer_id = p.farmer_id
where p.status in ('active', 'sold_out');

create view public.farmer_public as
select
  pr.id, pr.full_name, pr.avatar_url,
  fd.farm_name, fd.farm_size_acres, fd.main_crops,
  a.district, a.state,
  r.avg_rating,
  coalesce(r.ratings_count, 0) as ratings_count,
  pr.created_at as member_since
from public.profiles pr
left join public.farmer_details fd on fd.user_id = pr.id
left join public.addresses a on a.user_id = pr.id and a.is_default
left join public.farmer_ratings r on r.farmer_id = pr.id
where pr.role = 'farmer' and pr.onboarded;

create view public.open_demand as
select
  d.id, d.buyer_id, d.category, d.item_name, d.quantity, d.unit, d.target_price, d.needed_by, d.notes,
  d.district, d.state, d.status, d.created_at,
  pr.consumer_type as buyer_type,
  case
    when pr.consumer_type = 'industrial' then coalesce(nullif(trim(bd.business_name), ''), split_part(pr.full_name, ' ', 1))
    else split_part(pr.full_name, ' ', 1)
  end as buyer_label,
  round(d.lat::numeric, 2)::float8 as approx_lat,
  round(d.lng::numeric, 2)::float8 as approx_lng
from public.demand_requests d
join public.profiles pr on pr.id = d.buyer_id
left join public.buyer_details bd on bd.user_id = d.buyer_id
where d.status = 'open' and (d.needed_by is null or d.needed_by >= current_date);

-- ===== 20261004000002_functions.sql =====

-- Triggers and the three trusted operations (place_order, update_order_status, adjust_stock).
-- SECURITY DEFINER functions use an empty search_path and fully qualified names.

-- updated_at bookkeeping ------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
create trigger farmer_details_touch before update on public.farmer_details for each row execute function public.touch_updated_at();
create trigger buyer_details_touch before update on public.buyer_details for each row execute function public.touch_updated_at();
create trigger demand_touch before update on public.demand_requests for each row execute function public.touch_updated_at();

-- New auth user -> profile -------------------------------------------------------------------
-- The role comes from sign-up metadata and can never change afterwards (no column grant on role).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_meta jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_role public.user_role;
  v_ctype public.consumer_type;
begin
  v_role := case when v_meta ->> 'role' = 'farmer' then 'farmer' else 'consumer' end::public.user_role;
  if v_role = 'consumer' then
    v_ctype := case when v_meta ->> 'consumer_type' = 'industrial' then 'industrial' else 'individual' end::public.consumer_type;
  end if;

  insert into public.profiles (id, role, consumer_type, full_name, preferred_lang)
  values (
    new.id,
    v_role,
    v_ctype,
    left(coalesce(trim(v_meta ->> 'full_name'), ''), 120),
    case when v_meta ->> 'preferred_lang' = 'hi' then 'hi' else 'en' end
  );

  if v_role = 'farmer' then
    insert into public.farmer_details (user_id) values (new.id);
  else
    insert into public.buyer_details (user_id) values (new.id);
  end if;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Addresses: a new default address replaces the previous default ------------------------------
create or replace function public.addresses_single_default()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.is_default then
    update public.addresses set is_default = false
    where user_id = new.user_id and is_default and id <> new.id;
  end if;
  return new;
end;
$$;

create trigger addresses_single_default
  before insert or update of is_default on public.addresses
  for each row when (new.is_default)
  execute function public.addresses_single_default();

-- Produce ------------------------------------------------------------------------------------
create or replace function public.produce_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_addr public.addresses%rowtype;
begin
  if not exists (select 1 from public.profiles where id = new.farmer_id and role = 'farmer') then
    raise exception 'only_farmers_can_list' using errcode = '42501';
  end if;
  if new.qty_listed <= 0 then
    raise exception 'quantity_required' using errcode = '22023';
  end if;
  if new.min_order_qty > new.qty_listed then
    raise exception 'min_order_too_big' using errcode = '22023';
  end if;
  if new.status not in ('active', 'paused') then
    new.status := 'active';
  end if;
  new.qty_sold := 0;
  new.qty_reserved := 0;
  new.qty_spoiled := 0;

  select * into v_addr from public.addresses where user_id = new.farmer_id and is_default limit 1;
  if found then
    new.district := coalesce(new.district, v_addr.district);
    new.state := coalesce(new.state, v_addr.state);
    new.lat := coalesce(new.lat, v_addr.lat);
    new.lng := coalesce(new.lng, v_addr.lng);
  end if;
  return new;
end;
$$;

create trigger produce_before_insert
  before insert on public.produce
  for each row execute function public.produce_before_insert();

create or replace function public.produce_after_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.produce_log (produce_id, farmer_id, change_type, quantity)
  values (new.id, new.farmer_id, 'listed', new.qty_listed);
  return new;
end;
$$;

create trigger produce_after_insert
  after insert on public.produce
  for each row execute function public.produce_after_insert();

-- Keeps status honest: nothing left -> sold_out; stock back -> active again.
create or replace function public.produce_before_update()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_available numeric := new.qty_listed - new.qty_sold - new.qty_reserved - new.qty_spoiled;
begin
  if new.unit is distinct from old.unit and (old.qty_sold > 0 or old.qty_reserved > 0) then
    raise exception 'unit_locked' using errcode = '22023';
  end if;
  if new.min_order_qty > greatest(new.qty_listed, 0) then
    raise exception 'min_order_too_big' using errcode = '22023';
  end if;
  if new.status = 'active' and v_available <= 0 then
    new.status := 'sold_out';
  elsif new.status = 'sold_out' and v_available > 0 and old.status = 'sold_out' then
    new.status := 'active';
  elsif new.status = 'sold_out' and old.status <> 'sold_out' and v_available > 0 then
    new.status := old.status;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger produce_before_update
  before update on public.produce
  for each row execute function public.produce_before_update();

-- Demand: default the location to the buyer's saved address ----------------------------------
create or replace function public.demand_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_addr public.addresses%rowtype;
begin
  if not exists (select 1 from public.profiles where id = new.buyer_id and role = 'consumer') then
    raise exception 'only_buyers_can_post' using errcode = '42501';
  end if;
  new.status := 'open';
  if new.district is null or new.state is null then
    select * into v_addr from public.addresses where user_id = new.buyer_id and is_default limit 1;
    if found then
      new.district := coalesce(new.district, v_addr.district);
      new.state := coalesce(new.state, v_addr.state);
      new.lat := coalesce(new.lat, v_addr.lat);
      new.lng := coalesce(new.lng, v_addr.lng);
    end if;
  end if;
  return new;
end;
$$;

create trigger demand_before_insert
  before insert on public.demand_requests
  for each row execute function public.demand_before_insert();

-- Reviews: only the buyer of a delivered order, once ------------------------------------------
create or replace function public.reviews_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order public.orders%rowtype;
begin
  select * into v_order from public.orders where id = new.order_id;
  if not found or v_order.buyer_id is distinct from auth.uid() or v_order.status <> 'delivered' then
    raise exception 'cannot_review' using errcode = '42501';
  end if;
  new.buyer_id := v_order.buyer_id;
  new.farmer_id := v_order.farmer_id;
  new.reviewer_name := split_part(coalesce(v_order.buyer_name, ''), ' ', 1);
  return new;
end;
$$;

create trigger reviews_before_insert
  before insert on public.reviews
  for each row execute function public.reviews_before_insert();

-- place_order: the whole cart in one transaction ----------------------------------------------
-- p_items:    [{"produce_id": "...", "quantity": 4}, ...]
-- p_delivery: {"name","phone","line1","line2","village_city","district","state","pincode","lat","lng","notes"}
-- Rows are locked in id order, so two buyers racing for the last kilo cannot both get it.
create or replace function public.place_order(p_items jsonb, p_delivery jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_buyer public.profiles%rowtype;
  v_checkout uuid := gen_random_uuid();
  v_now timestamptz := now();
  v_farmer record;
  v_line record;
  v_prod public.produce%rowtype;
  v_order_id uuid;
  v_total numeric(14, 2);
  v_result jsonb := '[]'::jsonb;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  select * into v_buyer from public.profiles where id = v_uid;
  if not found or v_buyer.role <> 'consumer' then
    raise exception 'only_buyers_can_order' using errcode = '42501';
  end if;
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'invalid_cart' using errcode = '22023';
  end if;
  if coalesce(trim(p_delivery ->> 'name'), '') = ''
     or coalesce(trim(p_delivery ->> 'phone'), '') !~ '^[0-9+ -]{7,16}$'
     or coalesce(trim(p_delivery ->> 'line1'), '') = ''
     or coalesce(trim(p_delivery ->> 'village_city'), '') = ''
     or coalesce(trim(p_delivery ->> 'district'), '') = ''
     or coalesce(trim(p_delivery ->> 'state'), '') = ''
     or coalesce(trim(p_delivery ->> 'pincode'), '') !~ '^[0-9]{6}$' then
    raise exception 'invalid_delivery' using errcode = '22023';
  end if;

  -- Every item must point at a real listing.
  if exists (
    select 1
    from jsonb_array_elements(p_items) e
    left join public.produce p on p.id = (e ->> 'produce_id')::uuid
    where p.id is null
  ) then
    raise exception 'unavailable' using errcode = 'P0001';
  end if;

  perform 1
  from public.produce
  where id in (select (e ->> 'produce_id')::uuid from jsonb_array_elements(p_items) e)
  order by id
  for update;

  for v_farmer in
    select p.farmer_id, pr.full_name as farmer_name, pr.phone as farmer_phone
    from public.produce p
    join public.profiles pr on pr.id = p.farmer_id
    where p.id in (select (e ->> 'produce_id')::uuid from jsonb_array_elements(p_items) e)
    group by p.farmer_id, pr.full_name, pr.phone
    order by p.farmer_id
  loop
    insert into public.orders (
      checkout_id, buyer_id, farmer_id,
      delivery_name, delivery_phone, delivery_line1, delivery_line2, delivery_village_city,
      delivery_district, delivery_state, delivery_pincode, delivery_lat, delivery_lng, delivery_notes,
      buyer_name, buyer_type, farmer_name, farmer_phone, status_history
    )
    values (
      v_checkout, v_uid, v_farmer.farmer_id,
      left(trim(p_delivery ->> 'name'), 120),
      trim(p_delivery ->> 'phone'),
      left(trim(p_delivery ->> 'line1'), 200),
      nullif(left(trim(coalesce(p_delivery ->> 'line2', '')), 200), ''),
      left(trim(p_delivery ->> 'village_city'), 120),
      left(trim(p_delivery ->> 'district'), 120),
      left(trim(p_delivery ->> 'state'), 80),
      trim(p_delivery ->> 'pincode'),
      nullif(p_delivery ->> 'lat', '')::double precision,
      nullif(p_delivery ->> 'lng', '')::double precision,
      nullif(left(trim(coalesce(p_delivery ->> 'notes', '')), 500), ''),
      coalesce(nullif(v_buyer.full_name, ''), left(trim(p_delivery ->> 'name'), 120)),
      v_buyer.consumer_type,
      v_farmer.farmer_name,
      v_farmer.farmer_phone,
      jsonb_build_array(jsonb_build_object('status', 'placed', 'at', v_now, 'by', 'buyer'))
    )
    returning id into v_order_id;

    v_total := 0;
    for v_line in
      select (e ->> 'produce_id')::uuid as produce_id, sum((e ->> 'quantity')::numeric) as qty
      from jsonb_array_elements(p_items) e
      group by 1
      order by 1
    loop
      select * into v_prod from public.produce where id = v_line.produce_id;
      continue when v_prod.farmer_id <> v_farmer.farmer_id;

      if v_prod.status <> 'active' then
        raise exception 'unavailable' using errcode = 'P0001', detail = v_prod.name;
      end if;
      if v_line.qty is null or v_line.qty <= 0 then
        raise exception 'invalid_quantity' using errcode = '22023', detail = v_prod.name;
      end if;
      if v_line.qty < v_prod.min_order_qty then
        raise exception 'below_min_order' using errcode = 'P0001', detail = v_prod.name, hint = v_prod.min_order_qty::text;
      end if;
      if v_line.qty > v_prod.qty_available then
        raise exception 'insufficient_stock' using errcode = 'P0001', detail = v_prod.name, hint = v_prod.qty_available::text;
      end if;

      insert into public.order_items (order_id, produce_id, name, unit, unit_price, quantity)
      values (v_order_id, v_prod.id, v_prod.name, v_prod.unit, v_prod.price_per_unit, v_line.qty);

      update public.produce set qty_reserved = qty_reserved + v_line.qty where id = v_prod.id;

      insert into public.produce_log (produce_id, farmer_id, change_type, quantity, order_id)
      values (v_prod.id, v_prod.farmer_id, 'reserved', v_line.qty, v_order_id);

      v_total := v_total + round(v_line.qty * v_prod.price_per_unit, 2);
    end loop;

    update public.orders set total = v_total where id = v_order_id;
    v_result := v_result || jsonb_build_array(jsonb_build_object('order_id', v_order_id, 'farmer_id', v_farmer.farmer_id, 'total', v_total));
  end loop;

  return jsonb_build_object('checkout_id', v_checkout, 'orders', v_result);
end;
$$;

-- update_order_status: allowed moves per side, with the stock bookkeeping ----------------------
--   farmer: placed -> accepted | rejected; accepted -> packed | out_for_delivery | cancelled;
--           packed -> out_for_delivery | cancelled; out_for_delivery -> delivered
--   buyer:  placed | accepted -> cancelled
-- delivered moves reserved -> sold; rejected/cancelled releases the reservation.
create or replace function public.update_order_status(p_order_id uuid, p_status public.order_status)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_order public.orders%rowtype;
  v_actor text;
  v_ok boolean;
  v_item record;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'order_not_found' using errcode = 'P0002';
  end if;

  if v_uid is not null and v_uid = v_order.farmer_id then
    v_actor := 'farmer';
  elsif v_uid is not null and v_uid = v_order.buyer_id then
    v_actor := 'buyer';
  else
    raise exception 'not_allowed' using errcode = '42501';
  end if;

  v_ok := case v_actor
    when 'farmer' then
      (v_order.status = 'placed' and p_status in ('accepted', 'rejected'))
      or (v_order.status = 'accepted' and p_status in ('packed', 'out_for_delivery', 'cancelled'))
      or (v_order.status = 'packed' and p_status in ('out_for_delivery', 'cancelled'))
      or (v_order.status = 'out_for_delivery' and p_status = 'delivered')
    else
      v_order.status in ('placed', 'accepted') and p_status = 'cancelled'
  end;
  if not v_ok then
    raise exception 'invalid_transition' using errcode = '22023', detail = v_order.status::text || ' -> ' || p_status::text;
  end if;

  perform 1 from public.produce
  where id in (select produce_id from public.order_items where order_id = p_order_id)
  order by id
  for update;

  if p_status = 'delivered' then
    for v_item in select * from public.order_items where order_id = p_order_id and produce_id is not null loop
      update public.produce
      set qty_reserved = greatest(qty_reserved - v_item.quantity, 0),
          qty_sold = qty_sold + v_item.quantity
      where id = v_item.produce_id;
      insert into public.produce_log (produce_id, farmer_id, change_type, quantity, order_id)
      values (v_item.produce_id, v_order.farmer_id, 'sold', v_item.quantity, p_order_id);
    end loop;
  elsif p_status in ('rejected', 'cancelled') then
    for v_item in select * from public.order_items where order_id = p_order_id and produce_id is not null loop
      update public.produce
      set qty_reserved = greatest(qty_reserved - v_item.quantity, 0)
      where id = v_item.produce_id;
      insert into public.produce_log (produce_id, farmer_id, change_type, quantity, order_id)
      values (v_item.produce_id, v_order.farmer_id, 'released', v_item.quantity, p_order_id);
    end loop;
  end if;

  update public.orders
  set status = p_status,
      status_history = status_history || jsonb_build_array(jsonb_build_object('status', p_status, 'at', now(), 'by', v_actor)),
      delivered_at = case when p_status = 'delivered' then now() else delivered_at end,
      updated_at = now()
  where id = p_order_id;

  return (select to_jsonb(o) from public.orders o where o.id = p_order_id);
end;
$$;

-- adjust_stock: restock (+), spoiled (moves unsold to spoiled), adjusted (signed correction) ----
create or replace function public.adjust_stock(p_produce_id uuid, p_type public.ledger_type, p_qty numeric, p_note text default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_prod public.produce%rowtype;
begin
  if p_type not in ('restocked', 'spoiled', 'adjusted') then
    raise exception 'invalid_type' using errcode = '22023';
  end if;
  select * into v_prod from public.produce where id = p_produce_id for update;
  if not found or v_prod.farmer_id is distinct from auth.uid() then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  if v_prod.status = 'archived' then
    raise exception 'archived_listing' using errcode = '22023';
  end if;
  if p_qty is null or p_qty = 0 then
    raise exception 'invalid_quantity' using errcode = '22023';
  end if;

  if p_type = 'restocked' then
    if p_qty < 0 then
      raise exception 'invalid_quantity' using errcode = '22023';
    end if;
    update public.produce set qty_listed = qty_listed + p_qty where id = p_produce_id;
  elsif p_type = 'spoiled' then
    if p_qty < 0 or p_qty > v_prod.qty_available then
      raise exception 'exceeds_available' using errcode = 'P0001', hint = v_prod.qty_available::text;
    end if;
    update public.produce set qty_spoiled = qty_spoiled + p_qty where id = p_produce_id;
  else
    if v_prod.qty_available + p_qty < 0 then
      raise exception 'exceeds_available' using errcode = 'P0001', hint = v_prod.qty_available::text;
    end if;
    update public.produce set qty_listed = qty_listed + p_qty where id = p_produce_id;
  end if;

  insert into public.produce_log (produce_id, farmer_id, change_type, quantity, note)
  values (p_produce_id, v_prod.farmer_id, p_type, p_qty, nullif(left(trim(coalesce(p_note, '')), 300), ''));

  return (select to_jsonb(p) from public.produce p where p.id = p_produce_id);
end;
$$;

-- ===== 20261004000003_security.sql =====

-- Row-level security and privileges. The browser holds only the public anon key, so these
-- policies, column grants and the SECURITY DEFINER functions are the whole security boundary.

alter table public.profiles enable row level security;
alter table public.farmer_details enable row level security;
alter table public.buyer_details enable row level security;
alter table public.addresses enable row level security;
alter table public.produce enable row level security;
alter table public.produce_log enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.demand_requests enable row level security;
alter table public.reviews enable row level security;

-- Profiles and details: each user sees and edits only their own rows.
create policy "profiles: read own" on public.profiles
  for select to authenticated using (id = (select auth.uid()));
create policy "profiles: update own" on public.profiles
  for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));

create policy "farmer_details: own" on public.farmer_details
  for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "buyer_details: own" on public.buyer_details
  for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "addresses: own" on public.addresses
  for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- Produce: listings on the market are public; farmers manage their own.
create policy "produce: read market or own" on public.produce
  for select to anon, authenticated
  using (status in ('active', 'sold_out') or farmer_id = (select auth.uid()));
create policy "produce: farmers insert own" on public.produce
  for insert to authenticated
  with check (farmer_id = (select auth.uid()));
create policy "produce: farmers update own" on public.produce
  for update to authenticated
  using (farmer_id = (select auth.uid())) with check (farmer_id = (select auth.uid()));

create policy "produce_log: farmers read own" on public.produce_log
  for select to authenticated using (farmer_id = (select auth.uid()));

-- Orders: visible to the two parties; written only through place_order / update_order_status.
create policy "orders: parties read" on public.orders
  for select to authenticated
  using (buyer_id = (select auth.uid()) or farmer_id = (select auth.uid()));
create policy "order_items: parties read" on public.order_items
  for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = order_id and (o.buyer_id = (select auth.uid()) or o.farmer_id = (select auth.uid()))
  ));

-- Demand: buyers manage their own; everyone signed in reads open requests via public.open_demand.
create policy "demand: buyers read own" on public.demand_requests
  for select to authenticated using (buyer_id = (select auth.uid()));
create policy "demand: buyers insert own" on public.demand_requests
  for insert to authenticated with check (buyer_id = (select auth.uid()));
create policy "demand: buyers update own" on public.demand_requests
  for update to authenticated using (buyer_id = (select auth.uid())) with check (buyer_id = (select auth.uid()));
create policy "demand: buyers delete own" on public.demand_requests
  for delete to authenticated using (buyer_id = (select auth.uid()));

-- Reviews are public; the insert trigger checks the order was delivered to this buyer.
create policy "reviews: public read" on public.reviews
  for select to anon, authenticated using (true);
create policy "reviews: buyers insert own" on public.reviews
  for insert to authenticated with check (buyer_id = (select auth.uid()));

-- Privileges: start from nothing, then grant exactly what the app uses.
revoke all on all tables in schema public from anon, authenticated;
grant usage on schema public to anon, authenticated;

grant select on public.profiles to authenticated;
grant update (full_name, phone, avatar_url, preferred_lang, onboarded) on public.profiles to authenticated;

grant select on public.farmer_details, public.buyer_details to authenticated;
grant insert (user_id, farm_name, farm_size_acres, main_crops), update (farm_name, farm_size_acres, main_crops)
  on public.farmer_details to authenticated;
grant insert (user_id, business_name, business_type, gstin), update (business_name, business_type, gstin)
  on public.buyer_details to authenticated;

grant select, delete on public.addresses to authenticated;
grant insert (label, line1, line2, village_city, district, state, pincode, lat, lng, is_default),
      update (label, line1, line2, village_city, district, state, pincode, lat, lng, is_default)
  on public.addresses to authenticated;

grant select on public.produce to anon, authenticated;
grant insert (category, name, variety, description, unit, price_per_unit, qty_listed, min_order_qty,
              harvest_date, best_before, is_organic, images, status)
  on public.produce to authenticated;
grant update (category, name, variety, description, unit, price_per_unit, min_order_qty,
              harvest_date, best_before, is_organic, images, status)
  on public.produce to authenticated;

grant select on public.produce_log to authenticated;
grant select on public.orders, public.order_items to authenticated;

grant select, delete on public.demand_requests to authenticated;
grant insert (category, item_name, quantity, unit, target_price, needed_by, notes, district, state, lat, lng)
  on public.demand_requests to authenticated;
grant update (category, item_name, quantity, unit, target_price, needed_by, notes, status)
  on public.demand_requests to authenticated;

grant select on public.reviews to anon, authenticated;
grant insert (order_id, rating, comment) on public.reviews to authenticated;

grant select on public.market_listings, public.farmer_public, public.farmer_ratings to anon, authenticated;
grant select on public.open_demand to authenticated;

-- Functions: RPCs for signed-in users only; trigger functions are not callable at all.
revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function public.place_order(jsonb, jsonb) to authenticated;
grant execute on function public.update_order_status(uuid, public.order_status) to authenticated;
grant execute on function public.adjust_stock(uuid, public.ledger_type, numeric, text) to authenticated;

-- ===== 20261004000004_storage_realtime.sql =====

-- Photo buckets (public read) and live order updates.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('produce-images', 'produce-images', true, 2097152, array['image/webp', 'image/jpeg', 'image/png']),
  ('avatars', 'avatars', true, 1048576, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do nothing;

-- Uploads go to <bucket>/<user id>/<file>; users may only write inside their own folder.
create policy "photos: owners upload" on storage.objects
  for insert to authenticated
  with check (
    bucket_id in ('produce-images', 'avatars')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "photos: owners update" on storage.objects
  for update to authenticated
  using (bucket_id in ('produce-images', 'avatars') and (storage.foldername(name))[1] = (select auth.uid())::text)
  with check (bucket_id in ('produce-images', 'avatars') and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "photos: owners delete" on storage.objects
  for delete to authenticated
  using (bucket_id in ('produce-images', 'avatars') and (storage.foldername(name))[1] = (select auth.uid())::text);

-- Realtime: farmers get new orders live, buyers get status changes. RLS still applies per subscriber.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.orders;
    exception when duplicate_object then
      null;
    end;
  end if;
end;
$$;
