// Writes proofs/REPORT.md from the results `npm run prove` leaves in proofs/results/.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dir = path.join(root, "proofs/results");
const ORDER = ["search", "matching", "orders", "delivery", "rate"];
if (!existsSync(dir)) {
  console.error("No proofs/results yet: run npm run prove");
  process.exit(1);
}
const files = readdirSync(dir)
  .filter((f) => f.endsWith(".json"))
  .sort((a, b) => ORDER.indexOf(a.replace(".json", "")) - ORDER.indexOf(b.replace(".json", "")));
const groups = files.map((f) => JSON.parse(readFileSync(path.join(dir, f), "utf8")));

const theorems = groups.flatMap((g) => g.records.filter((r) => r.kind === "theorem"));
const checks = groups.flatMap((g) => g.records.filter((r) => r.kind === "check"));
const proved = theorems.filter((r) => r.expect === "proved" && r.outcome.status === "proved");
const findings = theorems.filter((r) => r.expect === "counterexample" && r.outcome.status === "counterexample");
const unexpected = theorems.filter((r) => r.outcome.status !== r.expect);
const failedChecks = checks.filter((c) => !c.passed);
const ok = unexpected.length === 0 && failedChecks.length === 0;

const esc = (s) => String(s).replace(/\|/g, "\\|");
const example = (e) =>
  Object.entries(e ?? {})
    .map(([k, v]) => `${k} = ${v}`)
    .join(", ");

let md = `# AnnSetu: proofs

Generated by \`npm run prove\` on ${new Date().toISOString().slice(0, 10)}. **${ok ? "All results as expected." : "SOME RESULTS ARE NOT AS EXPECTED."}**

- **${proved.length} theorems proved** for every possible input with the Z3 SMT solver.
- **${checks.length} checks passed${failedChecks.length ? ` (${failedChecks.length} failed)` : ""}**, which tie each model to the shipped code and database, or cover a finite case completely.
- **${findings.length} problems found** in the version deployed before the proofs, each kept as a counterexample and fixed.

## How to read this

Each model in \`proofs/models\` is written once and read two ways. Run on ordinary numbers, it is compared with the shipped TypeScript or with the real database (the "model is the code" checks). Run on Z3 terms, it becomes a formula, and a theorem is proved by asking Z3 for any input where the assumptions hold and the claim fails. If no such input exists, the theorem holds for **every** input, not just tested ones. For a *finding*, Z3 did produce such an input; it is shown as the counterexample.

What the proofs rely on:

- **Exact arithmetic.** Theorems are proved over exact rational numbers. The app's TypeScript uses 64-bit floating point, which can differ by about 10⁻¹² rupees; the database uses exact decimals.
- **The models are hand translations.** Each one is pinned to the shipped code by a check that runs both on many inputs (R0, M0a, M0b) or exhaustively (O7), or to the database by randomised runs (O8, D4).
- **Concurrency** rests on PostgreSQL row locks. \`place_order\`, \`update_order_status\` and \`adjust_stock\` lock each listing's row (\`select … for update\`, in id order) before reading or changing its stock, and hold the lock until commit. So orders arriving in the same instant take effect one after another, in some order, and O3 to O5 cover every such order. The \`produce_stock_non_negative\` check in the database refuses anything else.
- **Not modelled:** the distance formula (haversine) and the clock. Distances and hours enter the proofs as numbers.

`;

for (const g of groups) {
  md += `## ${g.group}\n\n| | Result | Statement |\n|---|---|---|\n`;
  for (const r of g.records) {
    if (r.kind === "theorem") {
      const res =
        r.outcome.status === "proved"
          ? `**Proved** (${r.outcome.ms} ms)`
          : r.outcome.status === "counterexample"
            ? r.expect === "counterexample"
              ? `**Finding**: counterexample ${example(r.outcome.example)}`
              : `**FAILED**: counterexample ${example(r.outcome.example)}`
            : `**Unknown** (${r.outcome.reason ?? "solver gave up"})`;
      md += `| **${r.id}** ${esc(r.title)} | ${esc(res)} | ${esc(r.statement)}${r.note ? ` *${esc(r.note)}*` : ""} |\n`;
    } else {
      md += `| **${r.id}** ${esc(r.title)} | ${r.passed ? "**Passed**" : "**FAILED**"} | ${esc(r.detail)} |\n`;
    }
  }
  md += "\n";
}

md += `## The problems the proofs found

| | What was wrong | Fix |
|---|---|---|
${findings.map((f) => `| **${f.id}** | ${esc(f.title.replace(/^Finding: (.)/, (_, c) => c.toUpperCase()))}. Counterexample: ${esc(example(f.outcome.example))} | ${esc(f.note ?? "")} |`).join("\n")}
`;

writeFileSync(path.join(root, "proofs/REPORT.md"), md);
console.log(`proofs/REPORT.md: ${proved.length} proved, ${checks.length} checks, ${findings.length} findings${ok ? "" : ", NOT ALL AS EXPECTED"}`);
if (!ok) process.exit(1);
