-- Item catalogue and sample prices. Generated from supabase/catalogue.json by scripts/build-catalogue-sql.mjs.
-- Shelf lives are rough estimates for ambient storage; replace them with published storage tables.

insert into public.items (id, category, name_en, name_hi, base_unit, shelf_life_hours, agmarknet_names, sort) values
  ('tomato', 'vegetables', 'Tomato', 'टमाटर', 'kg', 120, array['Tomato'], 0),
  ('potato', 'vegetables', 'Potato', 'आलू', 'kg', 2160, array['Potato'], 1),
  ('onion', 'vegetables', 'Onion', 'प्याज', 'kg', 1440, array['Onion'], 2),
  ('spinach', 'vegetables', 'Spinach', 'पालक', 'kg', 24, array['Spinach'], 3),
  ('cauliflower', 'vegetables', 'Cauliflower', 'फूलगोभी', 'kg', 96, array['Cauliflower'], 4),
  ('cabbage', 'vegetables', 'Cabbage', 'पत्ता गोभी', 'kg', 336, array['Cabbage'], 5),
  ('brinjal', 'vegetables', 'Brinjal', 'बैंगन', 'kg', 96, array['Brinjal'], 6),
  ('okra', 'vegetables', 'Okra (Lady finger)', 'भिंडी', 'kg', 72, array['Bhindi(Ladies Finger)'], 7),
  ('carrot', 'vegetables', 'Carrot', 'गाजर', 'kg', 336, array['Carrot'], 8),
  ('green-chilli', 'vegetables', 'Green chilli', 'हरी मिर्च', 'kg', 120, array['Green Chilli'], 9),
  ('capsicum', 'vegetables', 'Capsicum', 'शिमला मिर्च', 'kg', 168, array['Capsicum'], 10),
  ('cucumber', 'vegetables', 'Cucumber', 'खीरा', 'kg', 120, array['Cucumbar(Kheera)', 'Cucumber(Kheera)'], 11),
  ('bottle-gourd', 'vegetables', 'Bottle gourd', 'लौकी', 'kg', 168, array['Bottle gourd'], 12),
  ('bitter-gourd', 'vegetables', 'Bitter gourd', 'करेला', 'kg', 96, array['Bitter gourd'], 13),
  ('ridge-gourd', 'vegetables', 'Ridge gourd', 'तोरई', 'kg', 96, array['Ridgeguard(Tori)', 'Ridge gourd(Tori)'], 14),
  ('pumpkin', 'vegetables', 'Pumpkin', 'कद्दू', 'kg', 1440, array['Pumpkin'], 15),
  ('radish', 'vegetables', 'Radish', 'मूली', 'kg', 120, array['Raddish', 'Radish'], 16),
  ('green-peas', 'vegetables', 'Green peas', 'मटर', 'kg', 72, array['Peas Wet', 'Green Peas'], 17),
  ('beans', 'vegetables', 'French beans', 'बीन्स', 'kg', 96, array['Beans', 'French Beans (Frasbean)'], 18),
  ('coriander-leaves', 'vegetables', 'Coriander leaves', 'हरा धनिया', 'kg', 48, array['Coriander(Leaves)'], 19),
  ('methi-leaves', 'vegetables', 'Fenugreek leaves', 'मेथी', 'kg', 36, array['Methi(Leaves)'], 20),
  ('garlic', 'vegetables', 'Garlic', 'लहसुन', 'kg', 2160, array['Garlic'], 21),
  ('ginger', 'vegetables', 'Ginger', 'अदरक', 'kg', 720, array['Ginger(Green)'], 22),
  ('sweet-potato', 'vegetables', 'Sweet potato', 'शकरकंद', 'kg', 720, array['Sweet Potato'], 23),
  ('drumstick', 'vegetables', 'Drumstick', 'सहजन', 'kg', 96, array['Drumstick'], 24),
  ('beetroot', 'vegetables', 'Beetroot', 'चुकंदर', 'kg', 336, array['Beetroot'], 25),
  ('spring-onion', 'vegetables', 'Spring onion', 'हरा प्याज', 'kg', 48, array['Onion Green'], 26),
  ('other-vegetable', 'vegetables', 'Other vegetable', 'अन्य सब्ज़ी', 'kg', 96, '{}'::text[], 27),
  ('banana', 'fruits', 'Banana', 'केला', 'kg', 120, array['Banana', 'Banana - Green'], 28),
  ('mango', 'fruits', 'Mango', 'आम', 'kg', 168, array['Mango', 'Mango (Raw-Ripe)'], 29),
  ('apple', 'fruits', 'Apple', 'सेब', 'kg', 720, array['Apple'], 30),
  ('grapes', 'fruits', 'Grapes', 'अंगूर', 'kg', 120, array['Grapes'], 31),
  ('papaya', 'fruits', 'Papaya', 'पपीता', 'kg', 120, array['Papaya', 'Papaya (Raw)'], 32),
  ('guava', 'fruits', 'Guava', 'अमरूद', 'kg', 96, array['Guava'], 33),
  ('pomegranate', 'fruits', 'Pomegranate', 'अनार', 'kg', 720, array['Pomegranate'], 34),
  ('orange', 'fruits', 'Orange', 'संतरा', 'kg', 336, array['Orange'], 35),
  ('lemon', 'fruits', 'Lemon', 'नींबू', 'kg', 336, array['Lemon', 'Lime'], 36),
  ('watermelon', 'fruits', 'Watermelon', 'तरबूज', 'kg', 336, array['Water Melon'], 37),
  ('muskmelon', 'fruits', 'Muskmelon', 'खरबूजा', 'kg', 120, array['Karbuja(Musk Melon)'], 38),
  ('pineapple', 'fruits', 'Pineapple', 'अनानास', 'kg', 168, array['Pineapple'], 39),
  ('sapota', 'fruits', 'Sapota (Chikoo)', 'चीकू', 'kg', 96, array['Chikoos(Sapota)'], 40),
  ('coconut', 'fruits', 'Coconut', 'नारियल', 'piece', 1440, '{}'::text[], 41),
  ('other-fruit', 'fruits', 'Other fruit', 'अन्य फल', 'kg', 120, '{}'::text[], 42),
  ('wheat', 'grains', 'Wheat', 'गेहूँ', 'kg', 8760, array['Wheat'], 43),
  ('rice', 'grains', 'Rice', 'चावल', 'kg', 8760, array['Rice'], 44),
  ('paddy', 'grains', 'Paddy', 'धान', 'kg', 8760, array['Paddy(Dhan)(Common)', 'Paddy(Dhan)(Basmati)'], 45),
  ('maize', 'grains', 'Maize', 'मक्का', 'kg', 4320, array['Maize'], 46),
  ('bajra', 'grains', 'Pearl millet (Bajra)', 'बाजरा', 'kg', 4320, array['Bajra(Pearl Millet/Cumbu)'], 47),
  ('jowar', 'grains', 'Sorghum (Jowar)', 'ज्वार', 'kg', 4320, array['Jowar(Sorghum)'], 48),
  ('ragi', 'grains', 'Finger millet (Ragi)', 'रागी', 'kg', 4320, array['Ragi (Finger Millet)'], 49),
  ('barley', 'grains', 'Barley', 'जौ', 'kg', 4320, array['Barley (Jau)'], 50),
  ('other-grain', 'grains', 'Other grain', 'अन्य अनाज', 'kg', 4320, '{}'::text[], 51),
  ('chana', 'pulses', 'Chickpea (Chana)', 'चना', 'kg', 8760, array['Bengal Gram(Gram)(Whole)', 'Kabuli Chana(Chickpeas-White)'], 52),
  ('tur', 'pulses', 'Pigeon pea (Tur)', 'अरहर', 'kg', 8760, array['Arhar (Tur/Red Gram)(Whole)'], 53),
  ('moong', 'pulses', 'Green gram (Moong)', 'मूंग', 'kg', 8760, array['Green Gram (Moong)(Whole)'], 54),
  ('urad', 'pulses', 'Black gram (Urad)', 'उड़द', 'kg', 8760, array['Black Gram (Urd Beans)(Whole)'], 55),
  ('masoor', 'pulses', 'Lentil (Masoor)', 'मसूर', 'kg', 8760, array['Lentil (Masur)(Whole)'], 56),
  ('rajma', 'pulses', 'Kidney beans (Rajma)', 'राजमा', 'kg', 8760, '{}'::text[], 57),
  ('other-pulse', 'pulses', 'Other pulse', 'अन्य दाल', 'kg', 8760, '{}'::text[], 58),
  ('turmeric', 'spices', 'Turmeric', 'हल्दी', 'kg', 8760, array['Turmeric'], 59),
  ('dry-chilli', 'spices', 'Dry red chilli', 'लाल मिर्च', 'kg', 4320, array['Dry Chillies'], 60),
  ('coriander-seed', 'spices', 'Coriander seed', 'धनिया बीज', 'kg', 8760, array['Corriander seed', 'Coriander seed'], 61),
  ('cumin', 'spices', 'Cumin', 'जीरा', 'kg', 8760, array['Cummin Seed(Jeera)'], 62),
  ('black-pepper', 'spices', 'Black pepper', 'काली मिर्च', 'kg', 8760, array['Black pepper'], 63),
  ('other-spice', 'spices', 'Other spice', 'अन्य मसाला', 'kg', 8760, '{}'::text[], 64),
  ('groundnut', 'oilseeds', 'Groundnut', 'मूंगफली', 'kg', 4320, array['Groundnut', 'Groundnut (Split)'], 65),
  ('mustard', 'oilseeds', 'Mustard seed', 'सरसों', 'kg', 8760, array['Mustard'], 66),
  ('soybean', 'oilseeds', 'Soybean', 'सोयाबीन', 'kg', 8760, array['Soyabean'], 67),
  ('sesame', 'oilseeds', 'Sesame', 'तिल', 'kg', 8760, array['Sesamum(Sesame,Gingelly,Til)'], 68),
  ('sunflower-seed', 'oilseeds', 'Sunflower seed', 'सूरजमुखी', 'kg', 8760, array['Sunflower'], 69),
  ('other-oilseed', 'oilseeds', 'Other oilseed', 'अन्य तिलहन', 'kg', 8760, '{}'::text[], 70),
  ('milk', 'dairy', 'Milk', 'दूध', 'litre', 24, '{}'::text[], 71),
  ('curd', 'dairy', 'Curd', 'दही', 'kg', 48, '{}'::text[], 72),
  ('paneer', 'dairy', 'Paneer', 'पनीर', 'kg', 72, '{}'::text[], 73),
  ('ghee', 'dairy', 'Ghee', 'घी', 'kg', 4320, '{}'::text[], 74),
  ('butter', 'dairy', 'Butter', 'मक्खन', 'kg', 336, '{}'::text[], 75),
  ('other-dairy', 'dairy', 'Other dairy', 'अन्य डेयरी', 'kg', 48, '{}'::text[], 76),
  ('jaggery', 'others', 'Jaggery (Gur)', 'गुड़', 'kg', 4320, array['Gur(Jaggery)'], 77),
  ('honey', 'others', 'Honey', 'शहद', 'kg', 8760, '{}'::text[], 78),
  ('other', 'others', 'Other produce', 'अन्य उपज', 'kg', 96, '{}'::text[], 79);

insert into public.item_names (item_id, name) values
  ('tomato', 'tomato'),
  ('tomato', 'टमाटर'),
  ('tomato', 'tomatoes'),
  ('tomato', 'tomatoe'),
  ('tomato', 'tamatar'),
  ('tomato', 'tamaatar'),
  ('tomato', 'tamater'),
  ('tomato', 'tamato'),
  ('potato', 'potato'),
  ('potato', 'आलू'),
  ('potato', 'potatoes'),
  ('potato', 'potatoe'),
  ('potato', 'aloo'),
  ('potato', 'alu'),
  ('potato', 'aaloo'),
  ('potato', 'batata'),
  ('onion', 'onion'),
  ('onion', 'प्याज'),
  ('onion', 'onions'),
  ('onion', 'pyaz'),
  ('onion', 'pyaaz'),
  ('onion', 'piyaz'),
  ('onion', 'pyaj'),
  ('onion', 'piaz'),
  ('onion', 'kanda'),
  ('onion', 'kaanda'),
  ('onion', 'प्याज़'),
  ('onion', 'कांदा'),
  ('spinach', 'spinach'),
  ('spinach', 'पालक'),
  ('spinach', 'palak'),
  ('spinach', 'paalak'),
  ('cauliflower', 'cauliflower'),
  ('cauliflower', 'फूलगोभी'),
  ('cauliflower', 'gobhi'),
  ('cauliflower', 'gobi'),
  ('cauliflower', 'phool gobhi'),
  ('cauliflower', 'phoolgobhi'),
  ('cauliflower', 'phool gobi'),
  ('cauliflower', 'phulgobi'),
  ('cauliflower', 'फूल गोभी'),
  ('cauliflower', 'गोभी'),
  ('cabbage', 'cabbage'),
  ('cabbage', 'पत्ता गोभी'),
  ('cabbage', 'patta gobhi'),
  ('cabbage', 'pattagobhi'),
  ('cabbage', 'band gobhi'),
  ('cabbage', 'bandgobhi'),
  ('cabbage', 'patta gobi'),
  ('cabbage', 'बंद गोभी'),
  ('cabbage', 'पत्तागोभी'),
  ('brinjal', 'brinjal'),
  ('brinjal', 'बैंगन'),
  ('brinjal', 'eggplant'),
  ('brinjal', 'aubergine'),
  ('brinjal', 'baingan'),
  ('brinjal', 'bengan'),
  ('brinjal', 'baigan'),
  ('brinjal', 'vangi'),
  ('brinjal', 'vangan'),
  ('okra', 'okra (lady finger)'),
  ('okra', 'भिंडी'),
  ('okra', 'okra'),
  ('okra', 'lady finger'),
  ('okra', 'ladyfinger'),
  ('okra', 'ladies finger'),
  ('okra', 'bhindi'),
  ('okra', 'bhendi'),
  ('okra', 'bhindee'),
  ('okra', 'भिण्डी'),
  ('carrot', 'carrot'),
  ('carrot', 'गाजर'),
  ('carrot', 'carrots'),
  ('carrot', 'gajar'),
  ('carrot', 'gaajar'),
  ('green-chilli', 'green chilli'),
  ('green-chilli', 'हरी मिर्च'),
  ('green-chilli', 'green chili'),
  ('green-chilli', 'chilli'),
  ('green-chilli', 'chili'),
  ('green-chilli', 'hari mirch'),
  ('green-chilli', 'harimirch'),
  ('green-chilli', 'mirchi'),
  ('green-chilli', 'mirch'),
  ('green-chilli', 'मिर्च'),
  ('green-chilli', 'मिर्ची'),
  ('capsicum', 'capsicum'),
  ('capsicum', 'शिमला मिर्च'),
  ('capsicum', 'bell pepper'),
  ('capsicum', 'shimla mirch'),
  ('capsicum', 'shimla mirchi'),
  ('capsicum', 'simla mirch'),
  ('cucumber', 'cucumber'),
  ('cucumber', 'खीरा'),
  ('cucumber', 'kheera'),
  ('cucumber', 'khira'),
  ('cucumber', 'kakdi'),
  ('cucumber', 'ककड़ी'),
  ('bottle-gourd', 'bottle gourd'),
  ('bottle-gourd', 'लौकी'),
  ('bottle-gourd', 'lauki'),
  ('bottle-gourd', 'louki'),
  ('bottle-gourd', 'ghiya'),
  ('bottle-gourd', 'doodhi'),
  ('bottle-gourd', 'dudhi'),
  ('bottle-gourd', 'घीया'),
  ('bitter-gourd', 'bitter gourd'),
  ('bitter-gourd', 'करेला'),
  ('bitter-gourd', 'karela'),
  ('bitter-gourd', 'karella'),
  ('ridge-gourd', 'ridge gourd'),
  ('ridge-gourd', 'तोरई'),
  ('ridge-gourd', 'turai'),
  ('ridge-gourd', 'torai'),
  ('ridge-gourd', 'tori'),
  ('ridge-gourd', 'dodka'),
  ('ridge-gourd', 'तोरी'),
  ('pumpkin', 'pumpkin'),
  ('pumpkin', 'कद्दू'),
  ('pumpkin', 'kaddu'),
  ('pumpkin', 'kadu'),
  ('pumpkin', 'lal kaddu'),
  ('pumpkin', 'kashiphal'),
  ('radish', 'radish'),
  ('radish', 'मूली'),
  ('radish', 'mooli'),
  ('radish', 'muli'),
  ('green-peas', 'green peas'),
  ('green-peas', 'मटर'),
  ('green-peas', 'peas'),
  ('green-peas', 'matar'),
  ('green-peas', 'mattar'),
  ('green-peas', 'mutter'),
  ('green-peas', 'hara matar'),
  ('green-peas', 'हरा मटर'),
  ('beans', 'french beans'),
  ('beans', 'बीन्स'),
  ('beans', 'beans'),
  ('beans', 'green beans'),
  ('beans', 'sem'),
  ('beans', 'phali'),
  ('beans', 'farasbi'),
  ('beans', 'सेम'),
  ('beans', 'फली'),
  ('coriander-leaves', 'coriander leaves'),
  ('coriander-leaves', 'हरा धनिया'),
  ('coriander-leaves', 'coriander'),
  ('coriander-leaves', 'cilantro'),
  ('coriander-leaves', 'dhaniya'),
  ('coriander-leaves', 'dhania'),
  ('coriander-leaves', 'hara dhaniya'),
  ('coriander-leaves', 'kothimbir'),
  ('coriander-leaves', 'kothmir'),
  ('coriander-leaves', 'धनिया'),
  ('methi-leaves', 'fenugreek leaves'),
  ('methi-leaves', 'मेथी'),
  ('methi-leaves', 'fenugreek'),
  ('methi-leaves', 'methi'),
  ('methi-leaves', 'methi leaves'),
  ('garlic', 'garlic'),
  ('garlic', 'लहसुन'),
  ('garlic', 'lahsun'),
  ('garlic', 'lehsun'),
  ('garlic', 'lasun'),
  ('garlic', 'lasan'),
  ('ginger', 'ginger'),
  ('ginger', 'अदरक'),
  ('ginger', 'adrak'),
  ('ginger', 'adrakh'),
  ('ginger', 'aadrak'),
  ('sweet-potato', 'sweet potato'),
  ('sweet-potato', 'शकरकंद'),
  ('sweet-potato', 'shakarkandi'),
  ('sweet-potato', 'shakarkand'),
  ('sweet-potato', 'shakarkandh'),
  ('sweet-potato', 'शकरकंदी'),
  ('drumstick', 'drumstick'),
  ('drumstick', 'सहजन'),
  ('drumstick', 'drumsticks'),
  ('drumstick', 'moringa'),
  ('drumstick', 'sahjan'),
  ('drumstick', 'sehjan'),
  ('drumstick', 'shevga'),
  ('drumstick', 'सहजन फली'),
  ('beetroot', 'beetroot'),
  ('beetroot', 'चुकंदर'),
  ('beetroot', 'beet'),
  ('beetroot', 'chukandar'),
  ('beetroot', 'chukander'),
  ('spring-onion', 'spring onion'),
  ('spring-onion', 'हरा प्याज'),
  ('spring-onion', 'green onion'),
  ('spring-onion', 'hara pyaz'),
  ('spring-onion', 'hari pyaaz'),
  ('spring-onion', 'pyaz patti'),
  ('other-vegetable', 'other vegetable'),
  ('other-vegetable', 'अन्य सब्ज़ी'),
  ('other-vegetable', 'vegetable'),
  ('other-vegetable', 'sabzi'),
  ('other-vegetable', 'sabji'),
  ('other-vegetable', 'सब्ज़ी'),
  ('other-vegetable', 'सब्जी'),
  ('banana', 'banana'),
  ('banana', 'केला'),
  ('banana', 'bananas'),
  ('banana', 'kela'),
  ('banana', 'kele'),
  ('banana', 'केले'),
  ('mango', 'mango'),
  ('mango', 'आम'),
  ('mango', 'mangoes'),
  ('mango', 'aam'),
  ('mango', 'aamba'),
  ('mango', 'keri'),
  ('mango', 'केरी'),
  ('apple', 'apple'),
  ('apple', 'सेब'),
  ('apple', 'apples'),
  ('apple', 'seb'),
  ('apple', 'sev'),
  ('apple', 'saib'),
  ('grapes', 'grapes'),
  ('grapes', 'अंगूर'),
  ('grapes', 'grape'),
  ('grapes', 'angoor'),
  ('grapes', 'angur'),
  ('grapes', 'draksh'),
  ('papaya', 'papaya'),
  ('papaya', 'पपीता'),
  ('papaya', 'papita'),
  ('papaya', 'papeeta'),
  ('guava', 'guava'),
  ('guava', 'अमरूद'),
  ('guava', 'amrood'),
  ('guava', 'amrud'),
  ('guava', 'peru'),
  ('guava', 'jamrukh'),
  ('pomegranate', 'pomegranate'),
  ('pomegranate', 'अनार'),
  ('pomegranate', 'anar'),
  ('pomegranate', 'anaar'),
  ('pomegranate', 'dalimb'),
  ('orange', 'orange'),
  ('orange', 'संतरा'),
  ('orange', 'oranges'),
  ('orange', 'santra'),
  ('orange', 'santara'),
  ('orange', 'narangi'),
  ('lemon', 'lemon'),
  ('lemon', 'नींबू'),
  ('lemon', 'lime'),
  ('lemon', 'nimbu'),
  ('lemon', 'neembu'),
  ('lemon', 'nimboo'),
  ('lemon', 'limbu'),
  ('lemon', 'निंबू'),
  ('watermelon', 'watermelon'),
  ('watermelon', 'तरबूज'),
  ('watermelon', 'water melon'),
  ('watermelon', 'tarbooz'),
  ('watermelon', 'tarbuj'),
  ('watermelon', 'tarbuz'),
  ('watermelon', 'kalingad'),
  ('watermelon', 'तरबूज़'),
  ('muskmelon', 'muskmelon'),
  ('muskmelon', 'खरबूजा'),
  ('muskmelon', 'musk melon'),
  ('muskmelon', 'kharbuja'),
  ('muskmelon', 'kharbooja'),
  ('muskmelon', 'kharbooza'),
  ('pineapple', 'pineapple'),
  ('pineapple', 'अनानास'),
  ('pineapple', 'ananas'),
  ('pineapple', 'anannas'),
  ('sapota', 'sapota (chikoo)'),
  ('sapota', 'चीकू'),
  ('sapota', 'sapota'),
  ('sapota', 'chikoo'),
  ('sapota', 'chiku'),
  ('sapota', 'cheeku'),
  ('coconut', 'coconut'),
  ('coconut', 'नारियल'),
  ('coconut', 'nariyal'),
  ('coconut', 'nariyel'),
  ('coconut', 'naral'),
  ('other-fruit', 'other fruit'),
  ('other-fruit', 'अन्य फल'),
  ('other-fruit', 'fruit'),
  ('other-fruit', 'phal'),
  ('other-fruit', 'फल'),
  ('wheat', 'wheat'),
  ('wheat', 'गेहूँ'),
  ('wheat', 'gehu'),
  ('wheat', 'gehun'),
  ('wheat', 'gehoon'),
  ('wheat', 'gehoo'),
  ('wheat', 'gahu'),
  ('wheat', 'गेहूं'),
  ('wheat', 'गेहू'),
  ('rice', 'rice'),
  ('rice', 'चावल'),
  ('rice', 'chawal'),
  ('rice', 'chaval'),
  ('rice', 'basmati'),
  ('paddy', 'paddy'),
  ('paddy', 'धान'),
  ('paddy', 'dhan'),
  ('paddy', 'dhaan'),
  ('maize', 'maize'),
  ('maize', 'मक्का'),
  ('maize', 'corn'),
  ('maize', 'makka'),
  ('maize', 'makki'),
  ('maize', 'makai'),
  ('maize', 'मक्की'),
  ('bajra', 'pearl millet (bajra)'),
  ('bajra', 'बाजरा'),
  ('bajra', 'pearl millet'),
  ('bajra', 'bajra'),
  ('bajra', 'bajri'),
  ('jowar', 'sorghum (jowar)'),
  ('jowar', 'ज्वार'),
  ('jowar', 'sorghum'),
  ('jowar', 'jowar'),
  ('jowar', 'jawar'),
  ('jowar', 'juar'),
  ('ragi', 'finger millet (ragi)'),
  ('ragi', 'रागी'),
  ('ragi', 'finger millet'),
  ('ragi', 'ragi'),
  ('ragi', 'nachni'),
  ('ragi', 'mandua'),
  ('ragi', 'मंडुआ'),
  ('barley', 'barley'),
  ('barley', 'जौ'),
  ('barley', 'jau'),
  ('other-grain', 'other grain'),
  ('other-grain', 'अन्य अनाज'),
  ('other-grain', 'grain'),
  ('other-grain', 'anaj'),
  ('other-grain', 'अनाज'),
  ('chana', 'chickpea (chana)'),
  ('chana', 'चना'),
  ('chana', 'chickpea'),
  ('chana', 'chickpeas'),
  ('chana', 'gram'),
  ('chana', 'chana'),
  ('chana', 'channa'),
  ('chana', 'kabuli chana'),
  ('chana', 'chana dal'),
  ('chana', 'चने'),
  ('tur', 'pigeon pea (tur)'),
  ('tur', 'अरहर'),
  ('tur', 'pigeon pea'),
  ('tur', 'tur'),
  ('tur', 'toor'),
  ('tur', 'toor dal'),
  ('tur', 'tuar'),
  ('tur', 'arhar'),
  ('tur', 'arhar dal'),
  ('tur', 'तुअर'),
  ('tur', 'तूर'),
  ('moong', 'green gram (moong)'),
  ('moong', 'मूंग'),
  ('moong', 'green gram'),
  ('moong', 'moong'),
  ('moong', 'mung'),
  ('moong', 'moong dal'),
  ('moong', 'मूँग'),
  ('urad', 'black gram (urad)'),
  ('urad', 'उड़द'),
  ('urad', 'black gram'),
  ('urad', 'urad'),
  ('urad', 'urd'),
  ('urad', 'urad dal'),
  ('urad', 'उरद'),
  ('masoor', 'lentil (masoor)'),
  ('masoor', 'मसूर'),
  ('masoor', 'lentil'),
  ('masoor', 'lentils'),
  ('masoor', 'masoor'),
  ('masoor', 'masur'),
  ('masoor', 'masoor dal'),
  ('rajma', 'kidney beans (rajma)'),
  ('rajma', 'राजमा'),
  ('rajma', 'kidney beans'),
  ('rajma', 'rajma'),
  ('rajma', 'rajmah'),
  ('other-pulse', 'other pulse'),
  ('other-pulse', 'अन्य दाल'),
  ('other-pulse', 'pulse'),
  ('other-pulse', 'dal'),
  ('other-pulse', 'daal'),
  ('other-pulse', 'दाल'),
  ('turmeric', 'turmeric'),
  ('turmeric', 'हल्दी'),
  ('turmeric', 'haldi'),
  ('turmeric', 'halad'),
  ('dry-chilli', 'dry red chilli'),
  ('dry-chilli', 'लाल मिर्च'),
  ('dry-chilli', 'dry chilli'),
  ('dry-chilli', 'red chilli'),
  ('dry-chilli', 'lal mirch'),
  ('dry-chilli', 'sukhi mirch'),
  ('dry-chilli', 'सूखी मिर्च'),
  ('coriander-seed', 'coriander seed'),
  ('coriander-seed', 'धनिया बीज'),
  ('coriander-seed', 'coriander seeds'),
  ('coriander-seed', 'dhaniya beej'),
  ('coriander-seed', 'sukha dhaniya'),
  ('coriander-seed', 'साबुत धनिया'),
  ('cumin', 'cumin'),
  ('cumin', 'जीरा'),
  ('cumin', 'jeera'),
  ('cumin', 'jira'),
  ('cumin', 'zeera'),
  ('black-pepper', 'black pepper'),
  ('black-pepper', 'काली मिर्च'),
  ('black-pepper', 'pepper'),
  ('black-pepper', 'kali mirch'),
  ('black-pepper', 'kaali mirch'),
  ('other-spice', 'other spice'),
  ('other-spice', 'अन्य मसाला'),
  ('other-spice', 'spice'),
  ('other-spice', 'masala'),
  ('other-spice', 'मसाला'),
  ('groundnut', 'groundnut'),
  ('groundnut', 'मूंगफली'),
  ('groundnut', 'peanut'),
  ('groundnut', 'peanuts'),
  ('groundnut', 'moongphali'),
  ('groundnut', 'mungfali'),
  ('groundnut', 'moongfali'),
  ('groundnut', 'shengdana'),
  ('groundnut', 'मूँगफली'),
  ('mustard', 'mustard seed'),
  ('mustard', 'सरसों'),
  ('mustard', 'mustard'),
  ('mustard', 'sarson'),
  ('mustard', 'sarso'),
  ('mustard', 'rai'),
  ('mustard', 'राई'),
  ('soybean', 'soybean'),
  ('soybean', 'सोयाबीन'),
  ('soybean', 'soyabean'),
  ('soybean', 'soya'),
  ('soybean', 'soy'),
  ('sesame', 'sesame'),
  ('sesame', 'तिल'),
  ('sesame', 'til'),
  ('sesame', 'gingelly'),
  ('sunflower-seed', 'sunflower seed'),
  ('sunflower-seed', 'सूरजमुखी'),
  ('sunflower-seed', 'sunflower'),
  ('sunflower-seed', 'surajmukhi'),
  ('other-oilseed', 'other oilseed'),
  ('other-oilseed', 'अन्य तिलहन'),
  ('other-oilseed', 'oilseed'),
  ('other-oilseed', 'tilhan'),
  ('other-oilseed', 'तिलहन'),
  ('milk', 'milk'),
  ('milk', 'दूध'),
  ('milk', 'cow milk'),
  ('milk', 'buffalo milk'),
  ('milk', 'doodh'),
  ('milk', 'dudh'),
  ('curd', 'curd'),
  ('curd', 'दही'),
  ('curd', 'yogurt'),
  ('curd', 'yoghurt'),
  ('curd', 'dahi'),
  ('curd', 'dahee'),
  ('paneer', 'paneer'),
  ('paneer', 'पनीर'),
  ('paneer', 'cottage cheese'),
  ('paneer', 'panir'),
  ('ghee', 'ghee'),
  ('ghee', 'घी'),
  ('ghee', 'ghi'),
  ('ghee', 'desi ghee'),
  ('butter', 'butter'),
  ('butter', 'मक्खन'),
  ('butter', 'makhan'),
  ('butter', 'makkhan'),
  ('butter', 'loni'),
  ('other-dairy', 'other dairy'),
  ('other-dairy', 'अन्य डेयरी'),
  ('other-dairy', 'dairy'),
  ('other-dairy', 'डेयरी'),
  ('jaggery', 'jaggery (gur)'),
  ('jaggery', 'गुड़'),
  ('jaggery', 'jaggery'),
  ('jaggery', 'gur'),
  ('jaggery', 'gud'),
  ('jaggery', 'गुड'),
  ('honey', 'honey'),
  ('honey', 'शहद'),
  ('honey', 'shahad'),
  ('honey', 'shehad'),
  ('honey', 'madhu'),
  ('other', 'other produce'),
  ('other', 'अन्य उपज'),
  ('other', 'other'),
  ('other', 'anya'),
  ('other', 'अन्य')
on conflict do nothing;

-- Illustrative national prices, marked source = 'sample', so the rate suggestion and the price score
-- work before the live mandi feed runs. Live or manual prices always win over these.
insert into public.reference_prices (item_id, state, district, source, price_date, mandi_price) values
  ('tomato', '', '', 'sample', date '2026-10-01', 15),
  ('potato', '', '', 'sample', date '2026-10-01', 12),
  ('onion', '', '', 'sample', date '2026-10-01', 18),
  ('spinach', '', '', 'sample', date '2026-10-01', 15),
  ('cauliflower', '', '', 'sample', date '2026-10-01', 18),
  ('cabbage', '', '', 'sample', date '2026-10-01', 10),
  ('brinjal', '', '', 'sample', date '2026-10-01', 16),
  ('okra', '', '', 'sample', date '2026-10-01', 25),
  ('carrot', '', '', 'sample', date '2026-10-01', 20),
  ('green-chilli', '', '', 'sample', date '2026-10-01', 30),
  ('capsicum', '', '', 'sample', date '2026-10-01', 30),
  ('cucumber', '', '', 'sample', date '2026-10-01', 15),
  ('bottle-gourd', '', '', 'sample', date '2026-10-01', 12),
  ('bitter-gourd', '', '', 'sample', date '2026-10-01', 25),
  ('ridge-gourd', '', '', 'sample', date '2026-10-01', 22),
  ('pumpkin', '', '', 'sample', date '2026-10-01', 12),
  ('radish', '', '', 'sample', date '2026-10-01', 12),
  ('green-peas', '', '', 'sample', date '2026-10-01', 35),
  ('beans', '', '', 'sample', date '2026-10-01', 30),
  ('coriander-leaves', '', '', 'sample', date '2026-10-01', 40),
  ('methi-leaves', '', '', 'sample', date '2026-10-01', 30),
  ('garlic', '', '', 'sample', date '2026-10-01', 80),
  ('ginger', '', '', 'sample', date '2026-10-01', 50),
  ('sweet-potato', '', '', 'sample', date '2026-10-01', 20),
  ('drumstick', '', '', 'sample', date '2026-10-01', 40),
  ('beetroot', '', '', 'sample', date '2026-10-01', 20),
  ('spring-onion', '', '', 'sample', date '2026-10-01', 25),
  ('other-vegetable', '', '', 'sample', date '2026-10-01', 20),
  ('banana', '', '', 'sample', date '2026-10-01', 20),
  ('mango', '', '', 'sample', date '2026-10-01', 45),
  ('apple', '', '', 'sample', date '2026-10-01', 70),
  ('grapes', '', '', 'sample', date '2026-10-01', 50),
  ('papaya', '', '', 'sample', date '2026-10-01', 18),
  ('guava', '', '', 'sample', date '2026-10-01', 30),
  ('pomegranate', '', '', 'sample', date '2026-10-01', 80),
  ('orange', '', '', 'sample', date '2026-10-01', 40),
  ('lemon', '', '', 'sample', date '2026-10-01', 40),
  ('watermelon', '', '', 'sample', date '2026-10-01', 10),
  ('muskmelon', '', '', 'sample', date '2026-10-01', 18),
  ('pineapple', '', '', 'sample', date '2026-10-01', 30),
  ('sapota', '', '', 'sample', date '2026-10-01', 30),
  ('coconut', '', '', 'sample', date '2026-10-01', 18),
  ('other-fruit', '', '', 'sample', date '2026-10-01', 30),
  ('wheat', '', '', 'sample', date '2026-10-01', 24),
  ('rice', '', '', 'sample', date '2026-10-01', 32),
  ('paddy', '', '', 'sample', date '2026-10-01', 22),
  ('maize', '', '', 'sample', date '2026-10-01', 21),
  ('bajra', '', '', 'sample', date '2026-10-01', 24),
  ('jowar', '', '', 'sample', date '2026-10-01', 30),
  ('ragi', '', '', 'sample', date '2026-10-01', 35),
  ('barley', '', '', 'sample', date '2026-10-01', 22),
  ('other-grain', '', '', 'sample', date '2026-10-01', 25),
  ('chana', '', '', 'sample', date '2026-10-01', 55),
  ('tur', '', '', 'sample', date '2026-10-01', 90),
  ('moong', '', '', 'sample', date '2026-10-01', 80),
  ('urad', '', '', 'sample', date '2026-10-01', 75),
  ('masoor', '', '', 'sample', date '2026-10-01', 60),
  ('rajma', '', '', 'sample', date '2026-10-01', 90),
  ('other-pulse', '', '', 'sample', date '2026-10-01', 70),
  ('turmeric', '', '', 'sample', date '2026-10-01', 120),
  ('dry-chilli', '', '', 'sample', date '2026-10-01', 140),
  ('coriander-seed', '', '', 'sample', date '2026-10-01', 70),
  ('cumin', '', '', 'sample', date '2026-10-01', 220),
  ('black-pepper', '', '', 'sample', date '2026-10-01', 500),
  ('other-spice', '', '', 'sample', date '2026-10-01', 150),
  ('groundnut', '', '', 'sample', date '2026-10-01', 55),
  ('mustard', '', '', 'sample', date '2026-10-01', 55),
  ('soybean', '', '', 'sample', date '2026-10-01', 42),
  ('sesame', '', '', 'sample', date '2026-10-01', 120),
  ('sunflower-seed', '', '', 'sample', date '2026-10-01', 55),
  ('other-oilseed', '', '', 'sample', date '2026-10-01', 50),
  ('milk', '', '', 'sample', date '2026-10-01', 40),
  ('curd', '', '', 'sample', date '2026-10-01', 60),
  ('paneer', '', '', 'sample', date '2026-10-01', 280),
  ('ghee', '', '', 'sample', date '2026-10-01', 550),
  ('butter', '', '', 'sample', date '2026-10-01', 450),
  ('other-dairy', '', '', 'sample', date '2026-10-01', 60),
  ('jaggery', '', '', 'sample', date '2026-10-01', 40),
  ('honey', '', '', 'sample', date '2026-10-01', 250),
  ('other', '', '', 'sample', date '2026-10-01', 30);
